name: Pylint

on:
  push:
    branches:
      - main
      - 60-create-testsh
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]
    steps:
      - uses: actions/checkout@v1
      - run: ../../test.sh

